name: BdG
favicon: null
layout_spectrum: 0.36697
typography_spectrum: 0.268
title: Bruno de Georgio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191919'
    - '#fefefe'
    - '#818181'
    - '#b6b6b6'
    - '#c8a65a'
  brandStrength: 0.14597172127105296
  lightness: 0.26735765277408063
  saturation: 0.3134160393383354
  rhythmicContrast: 0.1164821102283895
purpose: []
